version: '3.2'

services:

#================================================================================================
# NGINX
#================================================================================================
  nginx:
    restart: always
    build:
      context: .
    links:
      - workspace-phpfpm
    ports:
      - "8113:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/nginx/phpfpm/laradock.conf:/etc/nginx/conf.d/default.conf   # phpfpm config path
      - ./log/nginx:/var/log/nginx                                           # log nginx
      - ./workspace:/var/www/html                                            # volume for data
    environment:
      - NGINX_VERSION=1.13.12

#================================================================================================
# WORKSPACE PHP-FPM
#================================================================================================
  workspace-phpfpm:
    restart: always
    image: dockerframework/workspace-phpfpm:latest
    ports:
      - "8115:80"
      - "8116:9090"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/php/php-fpm.conf:/usr/local/etc/php-fpm.conf                       # config path
      - ./config/php/php.ini:/usr/local/etc/php/php.ini                             # ini path
      - ./config/php/laradock-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini    # xdebug config
      - ./log/phpfpm:/var/log/phpfpm                                                # log phpfpm
      - ./vendor/composer.phar:/usr/local/bin/composer                              # vendor composer
      - ./vendor/deployer.phar:/usr/local/bin/dep                                   # vendor deployer
      - ./vendor/php-cs-fixer:/usr/local/bin/php-cs-fixer                           # vendor php-cs-fixer
      - ./data/laradock:/var/www/html                                               # volume for data
    environment:
      - NODE_VERSION=10.0.0
      - YARN_VERSION=1.6.0